general
{
}

log
{
  default_level ALL
}

forwarder
{
  default_hop_limit 0
}

tables
{
  cs_max_packets 65536
  cs_policy lru
  cs_unsolicited_policy drop-all

  strategy_choice
  {
    / /localhost/nfd/strategy/best-route
    /localhost /localhost/nfd/strategy/multicast
    /localhost/nfd /localhost/nfd/strategy/best-route
    /localhop /localhost/nfd/strategy/multicast
  }
}

face_system
{
  general
  {
    enable_congestion_marking yes
  }

  unix
  {
    path /var/run/nfd/nfd.sock
  }

  tcp
  {
    listen yes
    port 6363
    enable_v4 yes
    enable_v6 yes

    local
    {
      whitelist
      {
        subnet 127.0.0.0/8
        subnet ::1/128
        subnet 10.0.0.0/8
        subnet 172.16.0.0/12
        subnet 192.168.0.0/16
      }
      blacklist
      {
      }
    }
  }

  udp
  {
    listen yes
    port 6363
    enable_v4 yes
    enable_v6 yes
    idle_timeout 600
    unicast_mtu 1452
    mcast yes
  }
}

authorizations
{
  authorize
  {
    certfile any
    privileges
    {
      faces
      fib
      cs
      strategy-choice
    }
  }
}

rib
{
  localhost_security
  {
    trust-anchor
    {
      type any
    }
  }

  localhop_security
  {
    trust-anchor
    {
      type any
    }
  }

  prefix_announcement_validation
  {
    trust-anchor
    {
      type any
    }
  }
}
